language: cpp

# Install newer CMake version as the one that comes preinstalled doesn't
# support CMakeAddFortranSubdirectory.
before_install:
  - sudo apt-get install libc6:i386
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.2-Linux-i386.tar.gz

install:
  - tar xzf cmake-2.8.12.2-Linux-i386.tar.gz

script:
  - cmake-2.8.12.2-Linux-i386/bin/cmake .
  - make
